### ISSUE TITLE
Installation problem on OSX

### ISSUE THREAD

**Issue by crubier** [ros-infrastructure/rosinstall_generator#34]
On OSx, we cannot build `rosinstall-generator` anymore because its dependency `distribute` fails to build. `distribute` is deprecated and is now just a wrapper around `setuptools` which should be installed to run the installation process anyway (meaning adding it as a dependency is moot).

See also https://github.com/ovh/djehouty/issues/7

```
sudo -H pip install -U rosinstall_generator 
Collecting rosinstall-generator
  Using cached rosinstall_generator-0.1.11.tar.gz
Requirement already up-to-date: argparse in /usr/local/lib/python2.7/site-packages (from rosinstall-generator)
Requirement already up-to-date: catkin-pkg>=0.1.28 in /usr/local/lib/python2.7/site-packages (from rosinstall-generator)
Collecting distribute (from rosinstall-generator)
  Using cached distribute-0.7.3.zip
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/distribute.egg-info
    writing requirements to pip-egg-info/distribute.egg-info/requires.txt
    writing pip-egg-info/distribute.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/distribute.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/distribute.egg-info/dependency_links.txt
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-nmY9aI/distribute/setup.py", line 58, in <module>
        setuptools.setup(**setup_params)
      File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "setuptools/command/egg_info.py", line 177, in run
        writer = ep.load(installer=installer)
      File "pkg_resources.py", line 2241, in load
        if require: self.require(env, installer)
      File "pkg_resources.py", line 2254, in require
        working_set.resolve(self.dist.requires(self.extras),env,installer)))
      File "pkg_resources.py", line 2471, in requires
        dm = self._dep_map
      File "pkg_resources.py", line 2682, in _dep_map
        self.__dep_map = self._compute_dependencies()
      File "pkg_resources.py", line 2699, in _compute_dependencies
        from _markerlib import compile as compile_marker
    ImportError: No module named _markerlib
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-nmY9aI/distribute/

```

**Comment by wjwwood** [comment]
That sounds like the right thing to do. Can you open a pull request for the change?

**Comment by crubier** [comment]
#35

**Comment by dirk-thomas** [comment]
Addressed by #35.

**Comment by akhilaananthram** [comment]
I am still getting this issue for the same command when I try to install rosinstall-generator using pip 8.1.1 on OS X El Capitan.  I am also using setuptools version 20.7.0.

**Comment by dylanjbarth** [comment]
The patch hasn't been released yet so you will still see this bug if you try and install from pypi (I ran into this too). You can install from master `pip install git+git://github.com/ros-infrastructure/rosinstall_generator`

**Comment by dirk-thomas** [comment]
I released a new version: 0.1.12.
